services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: mnist_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: mnist_front
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - .:/app
