name: MLOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r mnist_project/requirements.txt

    - name: Run training pipeline (CNN)
      run: |
        sed -i 's/MODEL_TYPE = ".*"/MODEL_TYPE = "cnn"/' mnist_project/main_pipeline.py
        python mnist_project/main_pipeline.py

    - name: Check model file
      run: |
        test -f mnist_project/model/mnist_cnn.pt && echo "Modèle bien généré"
